apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"istio-ingressgateway","install.operator.istio.io/owning-resource":"installed-state","install.operator.istio.io/owning-resource-namespace":"istio-system","istio":"ingressgateway","operator.istio.io/component":"IngressGateways","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.3","release":"istio"},"name":"istio-ingressgateway","namespace":"istio-system"},"spec":{"ports":[{"name":"status-port","port":15020,"targetPort":15020},{"name":"http2","port":80,"targetPort":8080},{"name":"https","port":443,"targetPort":8443},{"name":"tcp","port":31400,"targetPort":31400},{"name":"tls","port":15443,"targetPort":15443}],"selector":{"app":"istio-ingressgateway","istio":"ingressgateway"},"type":"LoadBalancer"}}
  creationTimestamp: "2020-06-30T08:52:29Z"
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.3
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
  resourceVersion: "20801"
  selfLink: /api/v1/namespaces/istio-system/services/istio-ingressgateway
  uid: d96c3290-d610-4b29-bc6a-908a72e67c10
spec:
  clusterIP: 10.0.0.161
  externalTrafficPolicy: Cluster
  ports:
  - name: status-port
    nodePort: 35407
    port: 15020
    protocol: TCP
    targetPort: 15020
  - name: http2
    nodePort: 30180
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30090
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tcp
    nodePort: 33019
    port: 31400
    protocol: TCP
    targetPort: 31400
  - name: tls
    nodePort: 31203
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
